// GENERATOR CONSTS

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';


// NEW CONSTS

export const ADD_SHEET = 'ADD_SHEET';
export const LOAD_SPACE = 'LOAD_SPACE';
export const LOAD_SHEET = 'LOAD_SHEET';
export const ADD_SHEET_VIEW = 'ADD_SHEET_VIEW';

// SHEET CONSTS
export const UPDATE_CELL = 'UPDATE_CELL';
export const SHOW_ROW_MODAL = 'SHOW_ROW_MODAL';
export const CLOSE_ROW_MODAL = 'CLOSE_ROW_MODAL';
export const ADD_ROW = 'ADD_ROW';

// NAV CONSTS
export const CHANGE_SPACE_NAME = 'CHANGE_SPACE_NAME';
